#!/bin/bash

echo "🔧 CONTOH CARA UPDATE .env FILE:"
echo ""
echo "1. Edit file .env:"
echo "   nano .env"
echo ""
echo "2. Replace API keys dengan yang sebenar:"
echo ""
echo "# Contoh untuk setup minimum (OpenAI + Twilio):"
echo "OPENAI_API_KEY=\"sk-proj-abc123xyz789...\"" 
echo "TWILIO_SID=\"AC1234567890abcdef...\"" 
echo "TWILIO_TOKEN=\"your_auth_token_here\""
echo "TWILIO_PHONE_NUMBER=\"+60123456789\""
echo ""
echo "# Contoh untuk setup premium (OpenAI + Retell):"
echo "OPENAI_API_KEY=\"sk-proj-abc123xyz789...\""
echo "RETELL_API_KEY=\"key_abc123xyz789...\""
echo "RETELL_AGENT_ID=\"agent_abc123xyz789...\""
echo ""
echo "3. Save file (Ctrl+X, Y, Enter)"
echo ""
echo "4. Restart server:"
echo "   npm run dev"
echo ""
echo "5. Test calling system di https://salescallerai.lindy.site"

